"""add rversion field to user table

Revision ID: 7bac60f39781
Revises: 257c5951f94f
Create Date: 2020-07-10 16:19:31.569641

"""

# revision identifiers, used by Alembic.
revision = "7bac60f39781"
down_revision = "257c5951f94f"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("rversion", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "rversion")
    # ### end Alembic commands ###
